# 03 — Tercer estudio: Monte Carlo Matérn-LMC

Este notebook ejecuta el loop Monte Carlo con CBB pareado para una grilla de escenarios `(rho0, range_pix, anis_mode)`. La configuración inicial es pequeña para validar el flujo.

In [ ]:
# Ejecutar una vez si aparece ModuleNotFoundError
from pathlib import Path
import sys, subprocess
cwd = Path.cwd().resolve()
candidates = [cwd, cwd.parent, cwd.parent.parent]
ROOT = None
for path in candidates:
    if (path / "pyproject.toml").exists() and (path / "src" / "codispersion_bootstrap").exists():
        ROOT = path
        break
if ROOT is None:
    raise RuntimeError(f"No encontré la carpeta raíz del proyecto. Estoy parado en: {cwd}")
print("Carpeta raíz encontrada:", ROOT)
subprocess.check_call([sys.executable, "-m", "pip", "install", "-e", str(ROOT)])
print("Paquete instalado correctamente. Reinicia el kernel después de esta celda si es primera vez.")

In [1]:
from codispersion_bootstrap import build_H, run_monte_carlo_matern_lmc, monte_carlo_to_dataframe

In [3]:
H = build_H(hmax=2)
res = run_monte_carlo_matern_lmc(
    n1=128, n2=128,         # más pequeño para test
    H=H,
    rhos=[0.5],             # 1 valor de rho0
    ranges=[7.0],           # 1 rango
    anis_modes=["aniso"],   # 1 modo
    b=41, B=120,            # boot pequeño para test
    R=10,                   # 10 réplicas Monte Carlo (test)
    nu=1.0,
    angle_deg=45.0,
    anis_ratio=2.0,
        base_seed=2025,
)
df = monte_carlo_to_dataframe(res)
df

,h,rho0,range_pix,anis_mode,n,nu,angle_deg,anis_ratio,b,B,R,sampler,rho_hat_mean,rho_hat_var_mc,var_boot_mean,coverage,width_mean
0,"(1, 0)",0.5,7.0,aniso,"(128, 128)",1.0,45.0,2.0,41,120,10,CBB,0.511810,0.000258,0.000582,1.0,0.090858
1,"(0, 1)",0.5,7.0,aniso,"(128, 128)",1.0,45.0,2.0,41,120,10,CBB,0.504403,0.000332,0.000634,1.0,0.093937
2,"(1, 1)",0.5,7.0,aniso,"(128, 128)",1.0,45.0,2.0,41,120,10,CBB,0.499439,0.000348,0.000875,1.0,0.110190
3,"(-1, 1)",0.5,7.0,aniso,"(128, 128)",1.0,45.0,2.0,41,120,10,CBB,0.511617,0.000376,0.000393,1.0,0.074070
4,"(2, 0)",0.5,7.0,aniso,"(128, 128)",1.0,45.0,2.0,41,120,10,CBB,0.513860,0.000312,0.000504,0.9,0.084204
5,"(0, 2)",0.5,7.0,aniso,"(128, 128)",1.0,45.0,2.0,41,120,10,CBB,0.504493,0.000389,0.000551,1.0,0.087111
6,"(2, 2)",0.5,7.0,aniso,"(128, 128)",1.0,45.0,2.0,41,120,10,CBB,0.498492,0.000377,0.000747,1.0,0.101435
7,"(-2, 2)",0.5,7.0,aniso,"(128, 128)",1.0,45.0,2.0,41,120,10,CBB,0.515039,0.000522,0.000571,1.0,0.086727

In [4]:
df.to_csv("../results/tercer_estudio_mc_quick.csv", index=False)
df

,h,rho0,range_pix,anis_mode,n,nu,angle_deg,anis_ratio,b,B,R,sampler,rho_hat_mean,rho_hat_var_mc,var_boot_mean,coverage,width_mean
0,"(1, 0)",0.5,7.0,aniso,"(128, 128)",1.0,45.0,2.0,41,120,10,CBB,0.511810,0.000258,0.000582,1.0,0.090858
1,"(0, 1)",0.5,7.0,aniso,"(128, 128)",1.0,45.0,2.0,41,120,10,CBB,0.504403,0.000332,0.000634,1.0,0.093937
2,"(1, 1)",0.5,7.0,aniso,"(128, 128)",1.0,45.0,2.0,41,120,10,CBB,0.499439,0.000348,0.000875,1.0,0.110190
3,"(-1, 1)",0.5,7.0,aniso,"(128, 128)",1.0,45.0,2.0,41,120,10,CBB,0.511617,0.000376,0.000393,1.0,0.074070
4,"(2, 0)",0.5,7.0,aniso,"(128, 128)",1.0,45.0,2.0,41,120,10,CBB,0.513860,0.000312,0.000504,0.9,0.084204
5,"(0, 2)",0.5,7.0,aniso,"(128, 128)",1.0,45.0,2.0,41,120,10,CBB,0.504493,0.000389,0.000551,1.0,0.087111
6,"(2, 2)",0.5,7.0,aniso,"(128, 128)",1.0,45.0,2.0,41,120,10,CBB,0.498492,0.000377,0.000747,1.0,0.101435
7,"(-2, 2)",0.5,7.0,aniso,"(128, 128)",1.0,45.0,2.0,41,120,10,CBB,0.515039,0.000522,0.000571,1.0,0.086727