# 1. Preprocesamiento y Diagnóstico — Caso Real (A)

Incluye configuración TEST y FULL.

In [1]:
# Ejecutar una vez si aparece ModuleNotFoundError.
from pathlib import Path
import sys, subprocess
cwd = Path.cwd().resolve()
candidates = [cwd, cwd.parent, cwd.parent.parent]
ROOT = None
for p in candidates:
    if (p / "pyproject.toml").exists() and (p / "src" / "codispersion_real_case").exists():
        ROOT = p
        break
if ROOT is None:
    raise RuntimeError(f"No encontré la raíz del proyecto desde {cwd}")
subprocess.check_call([sys.executable, "-m", "pip", "install", "-e", str(ROOT)])
print("Proyecto instalado desde:", ROOT)

Proyecto instalado desde: C:\ONEDRIVECOPIA\OneDrive - Universidad Técnica Federico Santa María\Escritorio\Memoria\Documentos Necesarios\codispersion_real_case_template

## Test

In [1]:
from codispersion_real_case import run_real_preprocessing_A

# =========================
# CONFIGURACIÓN TEST
# =========================
DATA_DIR = "../data"
TEST = True       # True: recorte rápido; False: imágenes completas
CROP_N = 128

out_A = run_real_preprocessing_A(
    data_dir=DATA_DIR,
    test=TEST,
    crop_n=CROP_N,
    use_taper=True,
    border_px=8,
)

out_A["pre_diag"]["basic"]

  image    shape  min     max      mean       std
0     a  128x128  0.0  0.9999  0.608806  0.452609
1     b  128x128  0.0  0.9999  0.608149  0.453198
2     c  128x128  0.0  0.9999  0.600975  0.462210
3     d  128x128  0.0  0.9999  0.602429  0.460485

In [2]:
print("r_eff preprocesado:", out_A["pre_diag"]["r_eff"])
print("\nCodispersión (a,b)")
display(out_A["pre_diag"]["pairs"]["ab"]["codisp"])
print("\nCodispersión (c,d)")
display(out_A["pre_diag"]["pairs"]["cd"]["codisp"])

r_eff preprocesado: {'a': 7.2111, 'b': 7.2111, 'c': 7.2111, 'd': 7.2111}

Codispersión (a,b)

         h   rho_hat      m status
0  (-2, 2)  0.991043  16384     ok
1  (-1, 1)  0.980281  16384     ok
2   (0, 1)  0.967631  16384     ok
3   (0, 2)  0.984046  16384     ok
4   (1, 0)  0.965114  16384     ok
5   (1, 1)  0.981079  16384     ok
6   (2, 0)  0.983108  16384     ok
7   (2, 2)  0.991129  16384     ok

Codispersión (c,d)

         h   rho_hat      m status
0  (-2, 2)  0.992743  16384     ok
1  (-1, 1)  0.982937  16384     ok
2   (0, 1)  0.973024  16384     ok
3   (0, 2)  0.987015  16384     ok
4   (1, 0)  0.969111  16384     ok
5   (1, 1)  0.984415  16384     ok
6   (2, 0)  0.986054  16384     ok
7   (2, 2)  0.992892  16384     ok

## Caso Real

In [3]:
out_A_full = run_real_preprocessing_A(
     data_dir="../data",
     test=False,
     use_taper=True,
     border_px=8,
)
out_A_full["pre_diag"]["pairs"]["ab"]["codisp"]

         h   rho_hat       m status
0  (-2, 2)  0.964205  262144     ok
1  (-1, 1)  0.936658  262144     ok
2   (0, 1)  0.901135  262144     ok
3   (0, 2)  0.941196  262144     ok
4   (1, 0)  0.903871  262144     ok
5   (1, 1)  0.935696  262144     ok
6   (2, 0)  0.941790  262144     ok
7   (2, 2)  0.963978  262144     ok

In [5]:
print("r_eff preprocesado:", out_A_full["pre_diag"]["r_eff"])
print("\nCodispersión (a,b)")
display(out_A_full["pre_diag"]["pairs"]["ab"]["codisp"])
print("\nCodispersión (c,d)")
display(out_A_full["pre_diag"]["pairs"]["cd"]["codisp"])

r_eff preprocesado: {'a': 7.2111, 'b': 7.2111, 'c': 7.2111, 'd': 7.2111}

Codispersión (a,b)

         h   rho_hat       m status
0  (-2, 2)  0.964205  262144     ok
1  (-1, 1)  0.936658  262144     ok
2   (0, 1)  0.901135  262144     ok
3   (0, 2)  0.941196  262144     ok
4   (1, 0)  0.903871  262144     ok
5   (1, 1)  0.935696  262144     ok
6   (2, 0)  0.941790  262144     ok
7   (2, 2)  0.963978  262144     ok

Codispersión (c,d)

         h   rho_hat       m status
0  (-2, 2)  0.969657  262144     ok
1  (-1, 1)  0.944975  262144     ok
2   (0, 1)  0.917203  262144     ok
3   (0, 2)  0.951202  262144     ok
4   (1, 0)  0.913458  262144     ok
5   (1, 1)  0.944978  262144     ok
6   (2, 0)  0.949531  262144     ok
7   (2, 2)  0.969747  262144     ok