# 2. Preprocesamiento y Diagnóstico — Sintéticos controlados (B)

In [ ]:
# Ejecutar una vez si aparece ModuleNotFoundError.
from pathlib import Path
import sys, subprocess
cwd = Path.cwd().resolve()
candidates = [cwd, cwd.parent, cwd.parent.parent]
ROOT = None
for p in candidates:
    if (p / "pyproject.toml").exists() and (p / "src" / "codispersion_real_case").exists():
        ROOT = p
        break
if ROOT is None:
    raise RuntimeError(f"No encontré la raíz del proyecto desde {cwd}")
subprocess.check_call([sys.executable, "-m", "pip", "install", "-e", str(ROOT)])
print("Proyecto instalado desde:", ROOT)

## Test

In [1]:
from codispersion_real_case import run_synthetic_preprocessing_B

# TEST: n pequeño
out_B = run_synthetic_preprocessing_B(test=True, n=96)
out_B["diagnostics"]["summary"]

,model,X_std,Y_std,tileVarRatio_X,tileVarRatio_Y,r_eff_X(95%),r_eff_Y(95%),hmax,H,"rho(1,0)"
0,M1: alignment + noise,0.874885,0.751791,25.658572,15.501449,7.21110,7.21110,2,"[(-2, 2), (-1, 1), (0, 1), (0, 2), (1, 0), (1,...",0.938623
1,M2: different ranges,0.879118,0.937931,20.224568,38.387700,5.00000,7.61577,2,"[(-2, 2), (-1, 1), (0, 1), (0, 2), (1, 0), (1,...",0.139864
2,M3: anisotropy,0.904334,0.930199,52.979099,106.402996,7.61577,7.00000,2,"[(-2, 2), (-1, 1), (0, 1), (0, 2), (1, 0), (1,...",0.413877

In [2]:
for name, tab in out_B["diagnostics"]["codisp"].items():
    print("\n", name)
    display(tab)

 M1: alignment + noise

         h   rho_hat     m status
0  (-2, 2)  0.938956  9216     ok
1  (-1, 1)  0.933242  9216     ok
2   (0, 1)  0.922287  9216     ok
3   (0, 2)  0.925352  9216     ok
4   (1, 0)  0.938623  9216     ok
5   (1, 1)  0.930014  9216     ok
6   (2, 0)  0.940986  9216     ok
7   (2, 2)  0.935104  9216     ok

 M2: different ranges

         h   rho_hat     m status
0  (-2, 2)  0.163381  9216     ok
1  (-1, 1)  0.140008  9216     ok
2   (0, 1)  0.123064  9216     ok
3   (0, 2)  0.134575  9216     ok
4   (1, 0)  0.139864  9216     ok
5   (1, 1)  0.131094  9216     ok
6   (2, 0)  0.152108  9216     ok
7   (2, 2)  0.153758  9216     ok

 M3: anisotropy

         h   rho_hat     m status
0  (-2, 2)  0.380520  9216     ok
1  (-1, 1)  0.354844  9216     ok
2   (0, 1)  0.385032  9216     ok
3   (0, 2)  0.391024  9216     ok
4   (1, 0)  0.413877  9216     ok
5   (1, 1)  0.715942  9216     ok
6   (2, 0)  0.422196  9216     ok
7   (2, 2)  0.719356  9216     ok

## Sintético

In [3]:
from codispersion_real_case import run_synthetic_preprocessing_B
out_B_full = run_synthetic_preprocessing_B(test=False)
out_B_full["diagnostics"]["summary"]

,model,X_std,Y_std,tileVarRatio_X,tileVarRatio_Y,r_eff_X(95%),r_eff_Y(95%),hmax,H,"rho(1,0)"
0,M1: alignment + noise,0.962307,0.807840,4.274780,3.323455,7.61577,7.61577,2,"[(-2, 2), (-1, 1), (0, 1), (0, 2), (1, 0), (1,...",0.906794
1,M2: different ranges,0.954844,0.965434,2.377898,32.857429,5.00000,7.61577,2,"[(-2, 2), (-1, 1), (0, 1), (0, 2), (1, 0), (1,...",0.142903
2,M3: anisotropy,0.954659,0.963825,21.813423,5.744637,7.61577,7.00000,2,"[(-2, 2), (-1, 1), (0, 1), (0, 2), (1, 0), (1,...",0.358594

In [4]:
for name, tab in out_B_full["diagnostics"]["codisp"].items():
    print("\n", name)
    display(tab)

 M1: alignment + noise

         h   rho_hat      m status
0  (-2, 2)  0.916559  65536     ok
1  (-1, 1)  0.909360  65536     ok
2   (0, 1)  0.908251  65536     ok
3   (0, 2)  0.912075  65536     ok
4   (1, 0)  0.906794  65536     ok
5   (1, 1)  0.908572  65536     ok
6   (2, 0)  0.910792  65536     ok
7   (2, 2)  0.916403  65536     ok

 M2: different ranges

         h   rho_hat      m status
0  (-2, 2)  0.178369  65536     ok
1  (-1, 1)  0.153153  65536     ok
2   (0, 1)  0.147943  65536     ok
3   (0, 2)  0.160294  65536     ok
4   (1, 0)  0.142903  65536     ok
5   (1, 1)  0.145860  65536     ok
6   (2, 0)  0.155627  65536     ok
7   (2, 2)  0.170502  65536     ok

 M3: anisotropy

         h   rho_hat      m status
0  (-2, 2)  0.358830  65536     ok
1  (-1, 1)  0.333727  65536     ok
2   (0, 1)  0.362629  65536     ok
3   (0, 2)  0.369383  65536     ok
4   (1, 0)  0.358594  65536     ok
5   (1, 1)  0.660664  65536     ok
6   (2, 0)  0.365499  65536     ok
7   (2, 2)  0.663764  65536     ok