# 3. Preprocesamiento y Diagnóstico — Micro-datos Rank-1 (C)

In [ ]:
# Ejecutar una vez si aparece ModuleNotFoundError.
from pathlib import Path
import sys, subprocess
cwd = Path.cwd().resolve()
candidates = [cwd, cwd.parent, cwd.parent.parent]
ROOT = None
for p in candidates:
    if (p / "pyproject.toml").exists() and (p / "src" / "codispersion_real_case").exists():
        ROOT = p
        break
if ROOT is None:
    raise RuntimeError(f"No encontré la raíz del proyecto desde {cwd}")
subprocess.check_call([sys.executable, "-m", "pip", "install", "-e", str(ROOT)])
print("Proyecto instalado desde:", ROOT)

## Test

In [1]:
from codispersion_real_case import run_rank1_preprocessing_C

out_C = run_rank1_preprocessing_C(test=True, n=96)
out_C["diagnostics"]["summary"]

,case,r_eff_pre,hmax_pre,max|rho-±1|_pre,max|rho-±1|_post,max|Δrho|_taper
0,Rank-1 (Y = X),7.61577,2,0.0,2.220446e-16,2.220446e-16
1,Rank-1 (Y = -X),7.61577,2,0.0,2.220446e-16,2.220446e-16

In [2]:
for case, tabs in out_C["diagnostics"]["tables"].items():
    print("\n", case, "PRE")
    display(tabs["pre"])
    print(case, "POST")
    display(tabs["post"])

 Rank-1 (Y = X) PRE

         h  rho_hat     m status
0  (-2, 2)      1.0  9216     ok
1  (-1, 1)      1.0  9216     ok
2   (0, 1)      1.0  9216     ok
3   (0, 2)      1.0  9216     ok
4   (1, 0)      1.0  9216     ok
5   (1, 1)      1.0  9216     ok
6   (2, 0)      1.0  9216     ok
7   (2, 2)      1.0  9216     ok

Rank-1 (Y = X) POST

         h  rho_hat     m status
0  (-2, 2)      1.0  9216     ok
1  (-1, 1)      1.0  9216     ok
2   (0, 1)      1.0  9216     ok
3   (0, 2)      1.0  9216     ok
4   (1, 0)      1.0  9216     ok
5   (1, 1)      1.0  9216     ok
6   (2, 0)      1.0  9216     ok
7   (2, 2)      1.0  9216     ok

 Rank-1 (Y = -X) PRE

         h  rho_hat     m status
0  (-2, 2)     -1.0  9216     ok
1  (-1, 1)     -1.0  9216     ok
2   (0, 1)     -1.0  9216     ok
3   (0, 2)     -1.0  9216     ok
4   (1, 0)     -1.0  9216     ok
5   (1, 1)     -1.0  9216     ok
6   (2, 0)     -1.0  9216     ok
7   (2, 2)     -1.0  9216     ok

Rank-1 (Y = -X) POST

         h  rho_hat     m status
0  (-2, 2)     -1.0  9216     ok
1  (-1, 1)     -1.0  9216     ok
2   (0, 1)     -1.0  9216     ok
3   (0, 2)     -1.0  9216     ok
4   (1, 0)     -1.0  9216     ok
5   (1, 1)     -1.0  9216     ok
6   (2, 0)     -1.0  9216     ok
7   (2, 2)     -1.0  9216     ok

## Microdatos

In [3]:
out_C_full = run_rank1_preprocessing_C(test=False)
out_C_full["diagnostics"]["summary"]

,case,r_eff_pre,hmax_pre,max|rho-±1|_pre,max|rho-±1|_post,max|Δrho|_taper
0,Rank-1 (Y = X),7.61577,2,3.330669e-16,2.220446e-16,2.220446e-16
1,Rank-1 (Y = -X),7.61577,2,3.330669e-16,2.220446e-16,2.220446e-16

In [4]:
for case_full, tabs_full in out_C_full["diagnostics"]["tables"].items():
    print("\n", case_full, "PRE")
    display(tabs_full["pre"])
    print(case_full, "POST")
    display(tabs_full["post"])

 Rank-1 (Y = X) PRE

         h  rho_hat      m status
0  (-2, 2)      1.0  65536     ok
1  (-1, 1)      1.0  65536     ok
2   (0, 1)      1.0  65536     ok
3   (0, 2)      1.0  65536     ok
4   (1, 0)      1.0  65536     ok
5   (1, 1)      1.0  65536     ok
6   (2, 0)      1.0  65536     ok
7   (2, 2)      1.0  65536     ok

Rank-1 (Y = X) POST

         h  rho_hat      m status
0  (-2, 2)      1.0  65536     ok
1  (-1, 1)      1.0  65536     ok
2   (0, 1)      1.0  65536     ok
3   (0, 2)      1.0  65536     ok
4   (1, 0)      1.0  65536     ok
5   (1, 1)      1.0  65536     ok
6   (2, 0)      1.0  65536     ok
7   (2, 2)      1.0  65536     ok

 Rank-1 (Y = -X) PRE

         h  rho_hat      m status
0  (-2, 2)     -1.0  65536     ok
1  (-1, 1)     -1.0  65536     ok
2   (0, 1)     -1.0  65536     ok
3   (0, 2)     -1.0  65536     ok
4   (1, 0)     -1.0  65536     ok
5   (1, 1)     -1.0  65536     ok
6   (2, 0)     -1.0  65536     ok
7   (2, 2)     -1.0  65536     ok

Rank-1 (Y = -X) POST

         h  rho_hat      m status
0  (-2, 2)     -1.0  65536     ok
1  (-1, 1)     -1.0  65536     ok
2   (0, 1)     -1.0  65536     ok
3   (0, 2)     -1.0  65536     ok
4   (1, 0)     -1.0  65536     ok
5   (1, 1)     -1.0  65536     ok
6   (2, 0)     -1.0  65536     ok
7   (2, 2)     -1.0  65536     ok