# 4. Implementación Formal del Coeficiente

Verifica API vectorizada, tests Rank-1, sintéticos y smoke real.

In [ ]:
# Ejecutar una vez si aparece ModuleNotFoundError.
from pathlib import Path
import sys, subprocess
cwd = Path.cwd().resolve()
candidates = [cwd, cwd.parent, cwd.parent.parent]
ROOT = None
for p in candidates:
    if (p / "pyproject.toml").exists() and (p / "src" / "codispersion_real_case").exists():
        ROOT = p
        break
if ROOT is None:
    raise RuntimeError(f"No encontré la raíz del proyecto desde {cwd}")
subprocess.check_call([sys.executable, "-m", "pip", "install", "-e", str(ROOT)])
print("Proyecto instalado desde:", ROOT)

## Test

In [1]:
from codispersion_real_case import run_formal_implementation_checks

out_formal = run_formal_implementation_checks(
    data_dir="../data",
    test=True,
    crop_n=128,
)

print("Tests OK:", out_formal["tests_ok"])

✓ Unit tests (Rank-1 C): OK
M1: rho(1,0)=0.911 ⇒ OK
M2: |Δr_eff|=2.23, rho(1,0)=0.155 ⇒ OK
M3: anisY=8.42, anisX=2.08, rho(1,0)=0.321 ⇒ OK
Behavior tests (B):
Tests OK: True

In [2]:
out_formal["real_pairs"]["ab"]["codisp"]

         h   rho_hat      m status
0  (-2, 2)  0.991043  16384     ok
1  (-1, 1)  0.980281  16384     ok
2   (0, 1)  0.967631  16384     ok
3   (0, 2)  0.984046  16384     ok
4   (1, 0)  0.965114  16384     ok
5   (1, 1)  0.981079  16384     ok
6   (2, 0)  0.983108  16384     ok
7   (2, 2)  0.991129  16384     ok

## Implementación Formal

In [3]:
out_formal_full = run_formal_implementation_checks(data_dir="../data", test=False)
out_formal_full["real_pairs"]["cd"]["codisp"]

✓ Unit tests (Rank-1 C): OK
M1: rho(1,0)=0.911 ⇒ OK
M2: |Δr_eff|=2.23, rho(1,0)=0.155 ⇒ OK
M3: anisY=8.42, anisX=2.08, rho(1,0)=0.321 ⇒ OK
Behavior tests (B):

         h   rho_hat       m status
0  (-2, 2)  0.969657  262144     ok
1  (-1, 1)  0.944975  262144     ok
2   (0, 1)  0.917203  262144     ok
3   (0, 2)  0.951202  262144     ok
4   (1, 0)  0.913458  262144     ok
5   (1, 1)  0.944978  262144     ok
6   (2, 0)  0.949531  262144     ok
7   (2, 2)  0.969747  262144     ok

In [4]:
out_formal_full

{'tests_ok': True,
 'real_pairs': {'ab': {'H': [(-2, 2),
    (-1, 1),
    (0, 1),
    (0, 2),
    (1, 0),
    (1, 1),
    (2, 0),
    (2, 2)],
   'hmax': 2,
   'codisp':          h   rho_hat       m status
   0  (-2, 2)  0.964205  262144     ok
   1  (-1, 1)  0.936658  262144     ok
   2   (0, 1)  0.901135  262144     ok
   3   (0, 2)  0.941196  262144     ok
   4   (1, 0)  0.903871  262144     ok
   5   (1, 1)  0.935696  262144     ok
   6   (2, 0)  0.941790  262144     ok
   7   (2, 2)  0.963978  262144     ok},
  'cd': {'H': [(-2, 2),
    (-1, 1),
    (0, 1),
    (0, 2),
    (1, 0),
    (1, 1),
    (2, 0),
    (2, 2)],
   'hmax': 2,
   'codisp':          h   rho_hat       m status
   0  (-2, 2)  0.969657  262144     ok
   1  (-1, 1)  0.944975  262144     ok
   2   (0, 1)  0.917203  262144     ok
   3   (0, 2)  0.951202  262144     ok
   4   (1, 0)  0.913458  262144     ok
   5   (1, 1)  0.944978  262144     ok
   6   (2, 0)  0.949531  262144     ok
   7   (2, 2)  0.969747  262144     ok}},
 'ab_codisp_api': [{'h': (-2, 2),
   'rho': 0.9642054120806972,
   'Abar': 0.02179689726150319,
   'Bbar': 0.021605446964991008,
   'm': 262144,
   'status': 'ok'},
  {'h': (-1, 1),
   'rho': 0.9366579494899103,
   'Abar': 0.011900573867484394,
   'Bbar': 0.01176473891614691,
   'm': 262144,
   'status': 'ok'},
  {'h': (0, 1),
   'rho': 0.9011345498914903,
   'Abar': 0.007026105943541704,
   'Bbar': 0.006925599784415355,
   'm': 262144,
   'status': 'ok'},
  {'h': (0, 2),
   'rho': 0.9411963768304665,
   'Abar': 0.013021670689710841,
   'Bbar': 0.012886317868945826,
   'm': 262144,
   'status': 'ok'},
  {'h': (1, 0),
   'rho': 0.9038708860563349,
   'Abar': 0.007227590773216766,
   'Bbar': 0.0071118956241503495,
   'm': 262144,
   'status': 'ok'},
  {'h': (1, 1),
   'rho': 0.9356956378780262,
   'Abar': 0.011667885218700451,
   'Bbar': 0.011542737025825828,
   'm': 262144,
   'status': 'ok'},
  {'h': (2, 0),
   'rho': 0.941790100280626,
   'Abar': 0.013430980190128845,
   'Bbar': 0.013267553293241184,
   'm': 262144,
   'status': 'ok'},
  {'h': (2, 2),
   'rho': 0.9639782463970735,
   'Abar': 0.021591648528775032,
   'Bbar': 0.021411977233489764,
   'm': 262144,
   'status': 'ok'}],
 'cd_codisp_api': [{'h': (-2, 2),
   'rho': 0.969656779194471,
   'Abar': 0.02291807794827809,
   'Bbar': 0.02279780830680196,
   'm': 262144,
   'status': 'ok'},
  {'h': (-1, 1),
   'rho': 0.9449748606646261,
   'Abar': 0.011962862087472772,
   'Bbar': 0.011938440238416595,
   'm': 262144,
   'status': 'ok'},
  {'h': (0, 1),
   'rho': 0.9172027590738825,
   'Abar': 0.0070494545535206244,
   'Bbar': 0.0070828486061863295,
   'm': 262144,
   'status': 'ok'},
  {'h': (0, 2),
   'rho': 0.9512020608617657,
   'Abar': 0.013720256891315443,
   'Bbar': 0.0137005524142401,
   'm': 262144,
   'status': 'ok'},
  {'h': (1, 0),
   'rho': 0.9134582632764245,
   'Abar': 0.0071053601154924696,
   'Bbar': 0.0070853025452241505,
   'm': 262144,
   'status': 'ok'},
  {'h': (1, 1),
   'rho': 0.9449775275106952,
   'Abar': 0.01196277598434864,
   'Bbar': 0.011966299174035619,
   'm': 262144,
   'status': 'ok'},
  {'h': (2, 0),
   'rho': 0.9495311338480398,
   'Abar': 0.013943085324705526,
   'Bbar': 0.01389626117888895,
   'm': 262144,
   'status': 'ok'},
  {'h': (2, 2),
   'rho': 0.9697469296396817,
   'Abar': 0.022850140823735647,
   'Bbar': 0.022760180303101684,
   'm': 262144,
   'status': 'ok'}]}